.github/workflows/integration-testing.yml, codeception.dist.yml
Passes the github STEP_DEBUG secret to the integration test env, to allow for verbose codeception logging.
=> ci: use STEP_DEBUG flag on integration tests

CHANGELOG.md, composer.lock, src/Model/Seo.php, src/Type/WPObject/OpenGraph/Twitter.php, vendor/composer/installed.php
This PR fixes several issues when querying nodes for OpenGraph SEO data issues:
- fix: Prevent duplicate OpenGraph meta tags by clearing `RankMath` hooks before fetching.
- fix!: Rename `playerStreamContentTypee` to `playerStreamContentType`.
- fix: Allow `OpenGraphTwitter.appCountry` to resolve to `null`.
Addresses (partially) #15 .
=> fix: OpenGraph fixes

CHANGELOG.md, src/Model/ContentNodeSeo.php, src/Model/ContentTypeSeo.php, src/Model/Seo.php, src/Model/TermNodeSeo.php, src/Model/UserSeo.php, tests/functional/ContentNodeSeoQueryCept.php, vendor/composer/installed.php
This PR fixes several issues where the wrong WP globals were used to generate the RankMath `<head>` metadata and associated fields (like OpenGraph).
The issue manifested itself in several ways:
- When querying for a `listOf` objects, the first object would still be used to determine the `Paper()` class.
- When querying for a connected object type, the parent object would still be used to determine the `Paper()` class.
- When using a nonstandard WP Site URL (e.g `frontend.test.test` ), the REST API would automatically convert the url front to the backend (e.g. `backend.test.test/my-post` ), causing an error to be thrown when fetching the `fullHead`.
closes #19 
TL;DR instead of using RM's REST route to fetch the head, we're shimming the methods and generating it locally instead.
- fix: set …
=> fix: incorrect globals for generating <head>.

CHANGELOG.md, phpstan.neon.dist, wp-graphql-rank-math.php
Adds logic to check the that the versions of WPGraphQL and RankMath meet the plugin's minimum requirements.
=> dev: enforce plugin dep versions

CHANGELOG.md, src/Type/WPObject/OpenGraphMeta.php
This PR fixes the resolver used for `OpenGraphMeta.image` to correctly return the data needed to populate the `OpenGraphImage` type.
Rank Math stores the `url` in `$og['image']` and all the other properties in `$og['og:image']` 🤷‍♂️
- fix: pass necessary data to resolve `OpenGraphMeta.image` field.
=> fix: pass necessary data to resolve OpenGraphMeta.image

CHANGELOG.md, src/Model/ContentNodeSeo.php, tests/wpunit/ContentNodeSeoQueryTest.php
Implement fix for get_object_type() when object is a revision.
The function `get_object_type` returned null when using `asPreview` parameter. 
When using `asPreview`, the content type is `revision` and doesn't match the allowed types.
This pull request check if `$this->data->post_type` is a revision, and if this is the case it returns the parent post type.
You can try a query like this while being connected.
```
{
contentNode(id: "2011", idType: DATABASE_ID, asPreview: true) {
... on Page {
title
seo {
description
}
}
}
}
```
The graphql error happen after adding asPreview parameter.
=> fix: Use correct post type when querying for `ContentNodeSeo` on revisions.

CHANGELOG.md, wp-graphql-rank-math.php
Shows a conflict notice if `wp-graphql-yoast-seo` is installed.
Closes #42.
It checks for the `wp_gql_seo_build_content_type_data()` function since wp-graphql-yoast-seo doesn't use classes or namespaces 🤷
1. Install `wp-graphql-yoast-seo` (sometimes listed as "Add WPGraphQL SEO" or "WPGraphQL Yoast SEO Addon")
2. Confirm notice on plugins screen.
=> dev: show conflict notice for wp-graphql-yoast-seo

CHANGELOG.md, src/Model/ContentNodeSeo.php, src/Model/Seo.php, src/Model/TermNodeSeo.php, src/Model/UserSeo.php
This PR passes the `seo.title`, `.description`, and `.breadcrumbTitle` via `html_entities_decode()` when populating the respective WPGraphQL models.
Closes #50
=> dev: decode HTML entities

CHANGELOG.md, src/Model/Seo.php, src/Model/TermNodeSeo.php, src/Model/UserSeo.php, src/Type/WPInterface/Seo.php, tests/wpunit/CPTQueryTest.php, tests/wpunit/ContentTypeSeoQueryTest.php
When querying a custom taxonomy the seo data is wrong or is null. Expected behaviour would be for it to return the data set in the taxonomy
When querying a custom taxonomy to be able to display a taxonomy archive with a query such as this one:
```
query ExampleQuery {
exampletax(id: "example-tax-1", idType: SLUG) {
id
name
slug
examplecpts {
nodes {
title
slug
}
}
seo {
title
robots
description
canonicalUrl
openGraph {
locale
type
title
description
url
siteName
updatedTime
image {
url
width
height
type
}
twitterMeta {
card
title
image
}
}
}
}
}
```
the returned data is either wrong or null, such as this:
```
{
"data": {
"exampletax": {
"id": "dGVybToy",
"name": "Example Tax #1",
"slug": "example-tax-1",
"examplecpts": {
"nodes": [
{
"title": "Example Post #2",
"slug": "example-post-2"
}, …
```
=> Return expected data when querying seo data of custom taxonomy

.github/workflows/integration-testing.yml, .phpcs.xml.dist, CHANGELOG.md, README.md, bin/run-docker.sh, docker-compose.yml, readme.txt, vendor/composer/installed.php, wp-graphql-rank-math.php
Ensures compatibility with latest versions of WPGraphQL and Rank Math.
Additionally, changes the minimum version of WP to 5.6. This is _not_ a breaking change, as its the minimum version required by Rank Math v1.0.90.
=> chore: test against WP 6.3

CHANGELOG.md, src/Type/WPObject/Settings/Sitemap/ContentType.php, src/Type/WPObject/Settings/Sitemap/Taxonomy.php
I was getting an error saying: `array_map(): Argument #2 ($array) must be of type array, string given` when I have defined IDs to be excluded from the sitemap.
Getting an array by exploding the string and using `array_map` with an `absint` (like it's done in other places in the plugin).
=> Sitemap: `post__not_in` requires a value to be an array

CHANGELOG.md, src/Model/Settings.php, src/Type/WPObject/Settings/Sitemap/General.php, tests/wpunit/SettingsQueriesTest.php
This PR deprecates the `rankMathGeneral.sitemaps.general.canPingSearchEngines` field.
It was removed from [RM 1.0.211](https://rankmath.com/changelog/free/), since the feature is no longer supported by Google.
=> fix: deprecate `sitemaps.general.canPingSearchEngines`

phpstan/rank-math.stub, src/Model/Seo.php, src/Model/TermNodeSeo.php, src/Type/WPObject/OpenGraph/Product.php, src/Type/WPObject/OpenGraphMeta.php, tests/wpunit/ContentNodeSeoQueryTest.php, tests/wpunit/ContentTypeSeoQueryTest.php, tests/wpunit/SettingsQueriesTest.php
This PR:
1. Fixes the OG meta tag parsing for multidimensional terms.
2: Ensures that all RM modules are loaded before generating the tags.
Related to #66 
~The 👆 is caused due to RM moving around the filter calls internally.~
=> fix: improve SEO `head` data fetching and fix OG product meta.

CHANGELOG.md, composer.json, composer.lock
This PR pins WPBrowser to v3.4.x
https://wpbrowser.wptestkit.dev/migration/#staying-on-version-3-lower-than-35
=> chore: pin WPBrowser to <3.5

CHANGELOG.md, src/Model/Seo.php, src/Type/WPObject/OpenGraphMeta.php
This PR fixes a bug where an OpenGraph image passed as an URL would cause a fatal error during the meta tag parsing.
Fixes regression in #69
=> fix: Correctly resolve `seo.openGraph.image` field when parsed value is a string

src/Model/Settings.php, src/Type/WPObject/Settings/Meta/SocialMeta.php, tests/wpunit/SettingsQueriesTest.php
This PR exposes the `additionalProfiles` field to the social settings, i.e.
```
rankMathSettings {
meta {
social {
facebookPageUrl
twitterAuthorName
additionalProfiles <----
}
}
}
```
The Rank Math plugin allows us to add other social profiles apart from the Facebook URLs and the Twitter username. Therefore this field needs to be added to the GraphQL schema.
1. From the Rank Math Settings -> Titles & Meta -> Social Meta
2. Add a single URL or a list of comma-separated URLs to the `Additional Profiles` field
3. Use the query above in the GraphiQL IDE
=> feat: expose additionalProfiles field to the social settings

CHANGELOG.md, composer.json, composer.lock, phpstan.neon.dist, phpstan/constants.php, src/Modules/Redirection/Connection/RedirectionConnection.php, src/Modules/Redirection/Data/Connection/RedirectionConnectionResolver.php, src/Modules/Redirection/Model/Redirection.php, vendor/composer/installed.php, wp-graphql-rank-math.php
This PR updates the PHPStan config to use stricter type-checking rules, and remediates the newly-detected smells.
=> chore: implement PHPStan strict rules

CHANGELOG.md, activation.php, deactivation.php, src/Autoloader.php, src/Main.php, vendor/composer/autoload_classmap.php, vendor/composer/autoload_static.php, vendor/composer/installed.php, wp-graphql-rank-math.php
This PR refactors the plugin instantiation. More specifically:
- fix: Plugin versions in dependency check logic is now in sync with the actual plugin version requirements.
- chore!: Add `WPGraphQL/RankMath` namespace to root-level files: `activation.php`, `deactivation.php`, `wp-graphql-rank-math.php`, and cleanup the internal methods.
- chore: Move autoloader logic to `Autoloader` class.
=> chore!: refactor plugin instantiation

CHANGELOG.md, src/Model/ContentNodeSeo.php, src/Model/ContentTypeSeo.php, src/Model/Seo.php, src/Type/WPInterface/NodeWithSeo.php
This PR:
- Refactors breadcrumb generation so each `Model` handles its own generation.
- Improves the handling of `ContentTypeSeo` to account for Post Archives.
Fixes #81 in lieu of https://github.com/wp-graphql/wp-graphql/issues/2491
=> fix: improve `ContentTypeSeo` handling and breadcrumb generation

CHANGELOG.md, src/Model/Settings.php
Fix homepage description query null return
=> fix: correctly resolve `homepage.description`

CHANGELOG.md, README.md, readme.txt, src/Modules/Redirection/Data/Connection/RedirectionConnectionResolver.php, wp-graphql-rank-math.php
This PR bumps the minimum version of WPGraphQL to v1.26.0 in order to make use of the new API methods and improved internal lifecycle included in `AbstractConnectionResolver`.
A more stable lifecycle and improved performance.
=> chore!: bump minimum WPGraphQL and use new Connection Resolver API

CHANGELOG.md, docs/reference/queries.md, src/Type/WPInterface/NodeWithSeo.php, src/Type/WPObject/SeoObjects.php, src/Utils/Utils.php, tests/functional/UserSeoQueryCept.php, tests/wpunit/ContentNodeSeoQueryTest.php, tests/wpunit/UserSeoQueryTest.php, vendor/composer/installed.php
This PR improves the GraphQL schema by narrowing the `NodeWithSeo.seo` field type down to the implementation type (e.g. `RankMathContentNodeSeo`, `RankMathPostSeo` `RankMathUserSeo` etc.
That means instead of wrapping our queries with `...on *SEO { }`, we can access the fields directly on the schema.
Closes #79 
Introduced a new `Utils::overload_graphql_field_type()` to get around https://github.com/wp-graphql/wp-graphql/issues/3096
=> feat!: Narrow `seo` field types to their implementations.

.github/workflows/integration-testing.yml, CHANGELOG.md, bin/run-docker.sh, composer.json, readme.txt, wp-graphql-rank-math.php
This PR adds WP 6.6 to the test matrix, and updates the headers for 6.6.1
It also replaces `docker-compose` with `docker compose` commands, since it seems the deprecated command is no longer available on GH runners.
=> ci: test compatibility with WP 6.6.1

CHANGELOG.md, src/Type/WPObject/OpenGraph/Article.php, src/Type/WPObject/OpenGraph/Facebook.php, src/Type/WPObject/OpenGraph/Image.php, src/Type/WPObject/OpenGraph/Product.php, src/Type/WPObject/OpenGraph/Twitter.php
This PR guards against PHP fatal errors when resolving `OpenGraph` data, by defensively type casting any `resolve` callbacks that return a specific PHP type.
RM doesn't sanitize for types when using custom open graph values. This is readily apparent in RM pro, but also afffects RM free, due to how filters get applied.
Fixes #98
=> fix: improve openGraph type handling

codeception.dist.yml, tests/_support/AcceptanceTester.php, tests/_support/FunctionalTester.php, tests/_support/Helper/Acceptance.php, tests/_support/Helper/Functional.php, tests/_support/Helper/Unit.php, tests/_support/Helper/Wpunit.php, tests/_support/UnitTester.php, tests/_support/WpunitTester.php, tests/functional/ContentNodeSeoQueryCept.php, tests/functional/ContentTypeSeoQueryCept.php, tests/functional/TermNodeSeoQueryCept.php, tests/functional/UserSeoQueryCept.php, tests/unit.suite.dist.yml, tests/wpunit.suite.dist.yml, tests/wpunit/ContentNodeSeoQueryTest.php, tests/wpunit/MainTest.php, tests/wpunit/RedirectionConnectionQueriesTest.php, tests/wpunit/RedirectionQueriesTest.php, tests/wpunit/SettingsRedirectionQueriesTest.php
Fixes the namespaces for Codeception test files.
Removes warnings from `composer install`.
=> tests: fix namespaces for Codeception tests

CHANGELOG.md, src/Type/WPInterface/NodeWithSeo.php, tests/wpunit/ContentNodeSeoQueryTest.php
This PR fixes an issue in `NodeWithSeo` so the model is resolved using `Post::$databaseId` instead of `Post::$ID`
On private posts, the `Post::$ID` is protected, leading to potential fatal errors with strict types.
Fixes #108
=> fix: use `Post::$databaseId` to prevent fatals

CHANGELOG.md, src/Type/WPInterface/NodeWithSeo.php
This PR adds a `graphql_debug()` message when `null` is returned from a `Page.seo` on the Posts archive
Since WPGraphQL doesn't have an archive type, it treats the `page_for_posts` WP_Post object as a `ContentType` instead of content node. ( See the discussion on #2486 ). 
As that's not readily obvious, a debug message directing them to use `contentType` or `nodeByUri` will let them know that it's returning null for a reason. 
 
Closes #111
If the URI is null __and__ the a `Post` model is for the Posts Page, logs a message to `extensions.debug`
=> dev: add GraphQL Debug message to response when attempting to use `Page.seo` for the Posts Archive.
