- CHANGELOG.md
- phpstan/constants.php
- readme.txt
- wp-graphql-rank-math.php
> chore: version bump

- .github/workflows/code-quality.yml
- .github/workflows/code-standard.yml
- .github/workflows/integration-testing.yml
- .github/workflows/schema-linter.yml
- .github/workflows/upload-release.yml
- .github/workflows/upload-schema-artifact.yml
Updates workflows to use `ramsey/composer-install@v2` instead of manual caching. Also removes use of `pull_request_target` or need to use secrets to install deps.
> ci: update workflows

- CHANGELOG.md
- README.md
- phpstan/constants.php
- readme.txt
- wp-graphql-rank-math.php
> release: 0.0.6

- CHANGELOG.md
- composer.lock
- vendor/composer/installed.php
Updates composer deps to latest
> chore: update Composer deps

- CHANGELOG.md
- access-functions.php
- activation.php
- deactivation.php
- wp-graphql-rank-math.php
Makes global functions pluggable by wrapping them in `function_exists()` checks.
> dev: wrap global functions in `function_exists()`

- .github/workflows/integration-testing.yml
- codeception.dist.yml
Adds Coverage Reports to Codeclimate, and attempts to aggregate all all coverage reports together for coveralls.
> ci: add codeclimate coverage

- CHANGELOG.md
- README.md
- composer.lock
- phpstan/constants.php
- readme.txt
- vendor/composer/installed.php
- wp-graphql-rank-math.php
> release: v0.0.11

- CHANGELOG.md
- composer.json
- composer.lock
- vendor/composer/ClassLoader.php
- vendor/composer/autoload_real.php
- vendor/composer/installed.php
Updates Strauss to 0.14.0, and Composer dev-dependencies to their latest versions.
> chore: update Strauss to 0.14.0

- .github/workflows/integration-testing.yml
- CHANGELOG.md
- bin/run-docker.sh
- readme.txt
- wp-graphql-rank-math.php
Explicitly tests the plugin against the latest version of WP.
> ci: test against WordPress 6.2

- .github/ISSUE_TEMPLATE/Bug_report.yml
- .github/ISSUE_TEMPLATE/Feature_request.yml
- .github/ISSUE_TEMPLATE/config.yml
Updates the GH issue templates with some fixes and additional info.
> ci: update GitHub issue templates

- CHANGELOG.md
- README.md
- composer.lock
- phpstan/constants.php
- readme.txt
- vendor/composer/installed.php
- wp-graphql-rank-math.php
> release: v0.0.12

- CHANGELOG.md
- README.md
- composer.lock
- phpstan/constants.php
- readme.txt
- vendor/composer/installed.php
- wp-graphql-rank-math.php
> release: 0.0.14

- CHANGELOG.md
- README.md
- phpstan/constants.php
- readme.txt
- vendor/composer/installed.php
- wp-graphql-rank-math.php
> chore: version bump (v0.0.15)

- composer.json
- composer.lock
- src/CoreSchemaFilters.php
- src/Model/ContentNodeSeo.php
- src/Model/Seo.php
- tests/wpunit/CPTQueryTest.php
- vendor/composer/installed.php
Update deps to their latest versions and address the newly-exposed smells.
> chore: update deps and lint

- CHANGELOG.md
This PR adds a sponsorship notice to the changelog from [Red Rocks Web Development](https://redrockswebdevelopment.com/).
Thanks Red Rocks Web Development! 😍
https://github.com/sponsors/AxeWP/
> chore: add Red Rocks Web Development sponsorship to changelog.

- CHANGELOG.md
#69 didnt include a changelog 🤦‍♂️
> chore: update changelog for #69

- .github/workflows/integration-testing.yml
- CHANGELOG.md
- bin/run-docker.sh
- phpstan/constants.php
- readme.txt
- wp-graphql-rank-math.php
Adds WP 6.4.2 to the CI test matrix.
> ci: test against WP 6.4

- CHANGELOG.md
- README.md
- phpstan/constants.php
- readme.txt
- wp-graphql-rank-math.php
> release: v0.1.1

- CHANGELOG.md
- composer.lock
- src/Modules/Redirection/Data/Connection/RedirectionConnectionResolver.php
- src/Modules/Redirection/Data/Loader/RedirectionsLoader.php
- src/Type/WPInterface/Seo.php
- src/Type/WPObject/OpenGraph/Image.php
- src/Type/WPObject/OpenGraph/Product.php
- src/Type/WPObject/OpenGraph/Twitter.php
- src/Type/WPObject/OpenGraphMeta.php
- src/Type/WPObject/Settings/Sitemap/ContentType.php
- src/TypeRegistry.php
- vendor/composer/installed.php
- wp-graphql-rank-math.php
This PR update the composer dependencies, and fixes the newly-surfaced smells from WPGraphQL-Coding-Standards and PHPStan.
> chore: Update Composer dev-deps and fix newly-surfaced PHPCS smells

- .github/workflows/code-quality.yml
- .github/workflows/code-standard.yml
- .github/workflows/integration-testing.yml
- .github/workflows/schema-linter.yml
- .github/workflows/upload-release.yml
- .github/workflows/upload-schema-artifact.yml
- CHANGELOG.md
- bin/run-docker.sh
- readme.txt
- wp-graphql-rank-math.php
This PR:
- Cleans up and updates the GitHub Workflows to use the latest GH actions and native concurrency.
- Updates the CI to test against WP 6.5.0
> ci: update actions and test against WP 6.5.0

- CHANGELOG.md
- composer.json
- composer.lock
- vendor/composer/installed.php
Updates Strauss to the latest v0.17.0 and cleans up deps.
> ci: update Strauss to v0.17.0

- CHANGELOG.md
- wp-graphql-rank-math.php
Adds support for the new Plugin Dependencies header added in WP 6.5
> feat: add plugin dependencies header

- CHANGELOG.md
- README.md
- composer.lock
- phpstan/constants.php
- readme.txt
- vendor/composer/installed.php
- wp-graphql-rank-math.php
> release: 0.2.0

- CHANGELOG.md
- composer.json
- composer.lock
- src/Modules/Redirection/Data/Connection/RedirectionConnectionResolver.php
- tests/wpunit/RedirectionConnectionQueriesTest.php
- vendor/composer/installed.php
Updates composer deps to their latest versions, updates test compatibility and addresses newly exposed lints.
> chore: update composer dev-deps

- CHANGELOG.md
- README.md
- composer.json
- phpstan/constants.php
- readme.txt
- vendor/composer/installed.php
- wp-graphql-rank-math.php
> release: 0.3.0

- CHANGELOG.md
- README.md
- phpstan/constants.php
- readme.txt
- vendor/composer/installed.php
- wp-graphql-rank-math.php
> release: 0.3.2

- CHANGELOG.md
- README.md
- phpstan/constants.php
- readme.txt
- wp-graphql-rank-math.php
Version bump
WPGraphQL 2.0 is out.
> release: 0.3.3
